[workspace]
members = [
    "cosmos_gravity",
    "ethereum_gravity",
    "arcbnbbt",
    "gravity_proto",
    "gravity_utils",
    "metrics_exporter",
    "orchestrator",
    "proto_build",
    "relayer",
    "test_runner"
]
default-members = ["arcbnbbt"]

[patch.crates-io]
