# Orchestrator configuration options
[orchestrator]
# If the built-in relayer is enabled, this relayer is configured in the [relayer] section
relayer_enabled = false

# Relayer configuration options

# requests for batches sent on the Gravity Bridge side, consumes bridge chain
# tx fees
[relayer]
batch_request_mode = "EveryBatch"

[relayer.valset_relaying_mode]
mode = "Altruistic"

[relayer.batch_relaying_mode]
mode = "EveryBatch"

[metrics]
metrics_enabled = false
metrics_bind = "127.0.0.1:6631"
