[package]
name = "proto_build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

[dependencies]
prost = "0.9"
prost-build = "0.9"
regex = "1.5"
tonic = "0.6"
tonic-build = "0.6"
walkdir = "2"
